name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-go-backend:
    name: Run go tests (backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            backend

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run tests
        run: go test ./...


  tests-integration:
    name: Run integration tests (backend)
    runs-on: ubuntu-latest
    needs: test-go-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            backend
            firebase-emulator
            tests-integration

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests with Docker Compose
        run: |
          docker compose -f ./tests-integration/compose.yml --project-directory . up --build --abort-on-container-exit --exit-code-from tests-runner
